package exception;

public class Exception2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int arr[] = {1,2,3,4,5};
		try {
			int a = arr[8];
			
		}
		catch(ArrayIndexOutOfBoundsException ae) {
			
		}
	}

}
